PREFIX	?= arm-none-eabi
CC		= $(PREFIX)-gcc
LD		= $(PREFIX)-gcc
AR		= $(PREFIX)-ar
OBJCOPY	= $(PREFIX)-objcopy
OBJDUMP	= $(PREFIX)-objdump
GDB		= $(PREFIX)-gdb
SIZE    = $(PREFIX)-size

# optional: pick one
SIZEFLAGS ?= --format=berkeley
# SIZEFLAGS ?= -A


ifeq ($(PLATFORM),stm32)
include stm32f407.mk
else
include qemu.mk
endif

CFLAGS += -c -fdump-rtl-dfinish -fstack-usage 


# All C and asm sources in this directory
SRCS_C := $(wildcard *.c)
SRCS_S := $(wildcard *.s *.S)

# Map foo.c -> obj/foo.c.o, foo.s -> obj/foo.s.o, foo.S -> obj/foo.S.o
OBJS   := $(patsubst %.c,obj/%.c.o,$(SRCS_C)) \
          $(patsubst %.s,obj/%.s.o,$(SRCS_S)) \
          $(patsubst %.S,obj/%.S.o,$(SRCS_S))


LINKDEPS += $(OBJS) #obj/ref.c.o obj/m4.S.o


obj/_ELFNAME_%.o: $(LINKDEPS)
	@echo "  GEN     $@"
	$(Q)echo "const char _elf_name[] = \"$(ELFNAME)\";" | \
		$(CC) -x c -c -o $@ $(filter-out -g3,$(CFLAGS)) -

elf/%.elf: obj/_ELFNAME_%.elf.o $(LINKDEPS)
	@echo "  LD      $@"
	$(Q)[ -d $(@D) ] || mkdir -p $(@D)
	$(Q)$(LD) $(LDFLAGS) -o $@ $(filter %.o,$^) -Wl,--start-group $(LDLIBS) -Wl,--end-group
	@echo "  SIZE    $@"
	$(Q)$(SIZE) $(SIZEFLAGS) $@
	
obj/%.a:
	@echo "  AR      $@"
	$(Q)[ -d $(@D) ] || mkdir -p $(@D)
	$(Q)$(AR) rcs $@ $(filter %.o,$^)

bin/%.bin: elf/%.elf
	@echo "  OBJCOPY $@"
	$(Q)[ -d $(@D) ] || mkdir -p $(@D)
	$(Q)$(OBJCOPY) -Obinary $< $@

bin/%.hex: elf/%.elf
	@echo "  OBJCOPY $@"
	$(Q)[ -d $(@D) ] || mkdir -p $(@D)
	$(Q)$(OBJCOPY) -Oihex $< $@

obj/%.c.o: %.c
	@echo "  CC      $@"
	$(Q)[ -d $(@D) ] || mkdir -p $(@D)
	$(Q)$(CC) -c -o $@ $(CFLAGS) $<

obj/%.S.o: %.S
	@echo "  AS      $@"
	$(Q)[ -d $(@D) ] || mkdir -p $(@D)
	$(Q)$(CC) -c -o $@ $(CFLAGS) $<

obj/%.s.o: %.s
	@echo "  AS      $@"
	$(Q)[ -d $(@D) ] || mkdir -p $(@D)
	$(Q)$(CC) -c -o $@ $(CFLAGS) $<


clean:
	find . -name \*.o -type f -exec rm -f {} \;
	find . -name \*.d -type f -exec rm -f {} \;
	rm -rf obj/ bin/ elf/